export { default as Navbar } from './navbar'
export { default as Landing } from './landing'
export { default as Projects } from './projects'
export { default as AboutMe } from './about-me'
export { default as Connect } from './connect'
export { default as Footer } from './footer'
